# firewall_setting
# - main.yml
#   - setup_fwports.yml
---
- name: setup firewall ports
  firewalld:
    zone: "{{ item.zone }}"
    port: "{{ item.port }}"
    permanent: True
    state: enabled
  register: fw_port_result

- name: set_fact firewalld restart flag
  set_fact:
    fwd_restart_flag: "{{ fwd_restart_flag or fw_port_result.changed }}"

