# firewall_setting
# - main.yml
#   - setup_fwservices.yml
---
- name: setup firewall services
  firewalld:
    zone: "{{ item.0.zone }}"
    service: "{{ item.1.name }}"
    permanent: True
    state: enabled
  register: fw_service_result

- name: set_fact firewalld restart flag
  set_fact:
    fwd_restart_flag: "{{ fwd_restart_flag or fw_service_result.changed }}"
