# ssh_setting
# - main.yml
---
- name: set_fact sshd restart flag
  set_fact:
    sshd_restart_flag: False

- include_tasks: setup_ssh_authkey.yml
  with_items: "{{ ssh_params.ssh_pubkes }}"

- include_tasks: setup_sshd_config_replace.yml
  with_items: "{{ ssh_params.sshd_config_replace }}"

- include_tasks: setup_sshd_config_linein.yml
  with_items: "{{ ssh_params.sshd_config_linein }}"

- name: restart sshd.service
  systemd:
    name: "sshd.service"
    state: "restarted"
  when: sshd_restart_flag == True