# yum_install_update
# main.yml
---
- name: yum install
  yum:
    name: "{{ item }}"
    state: present
  with_items:
  - "{{ yum_packages }}"

- name: yum update
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
  - "{{ yum_packages }}"