# samba_setting
# - main.yml
---
#- name: set samba user password

- name: template /etc/samba/smb.conf
  template:
    src: "{{ samba_params.smbconf_params.file }}"
    dest: "/etc/samba/smb.conf"
    owner: "root"
    group: "root"
    mode: "0644"
    backup: yes

- name: check if samba user exists in OS
  command: id {{ samba_params.samba_user }}
  changed_when: False

- name: set samba user's password by expect
  expect:
    command: pdbedit -a -u {{ samba_params.samba_user }}
    responses:
      new password: "{{ samba_params.samba_userpass }}"
      samba_userpass: "{{ samba_params.samba_userpass }}"

- name: check if samba user exists in tdbsam
  command: pdbedit -u {{ samba_params.samba_user }}
  changed_when: False
  register: result_pdbedit

- debug: var=result_pdbedit.stdout_lines

- name: restart smb.service
  systemd:
    name: "{{ item }}"
    state: "restarted"
  with_items:
    - "smb.service"
    - "nmb.service"

- name: selinux
  command: chcon -t samba_share_t {{ item }} -R
  with_items: "{{ samba_params.smb_dir_list }}"
